### PR TITLE
Remove Legacy Properties Option

### PR DESCRIPTION
**Pull request by prakashpp**

### CODE REVIEW

**Review by dmosorast — APPROVED** [review]
Looks good! As long as it doesn't break locally due to any unforeseen issues, I'm good to deploy it.

**Comment by prakashpp** [comment]
@dmosorast working locally. Can you deploy it or I have to release first?

**Comment by prakashpp** [comment]
@dmosorast I already released module on pypi, please trigger deploy.

**Comment by dmosorast** [comment]
@prakashpp Released version 0.1.4. It should pick it up on the next run.

**Pull request merged**
